#!/bin/bash


SRC_F_PREFIX="/srv/nvme0/file512kb"
NUM_FILES=500
for m in $(seq 1 3)
do
	DST_F_PREFIX="/srv/nvme${m}/file512kb"

	for n in $(seq 1 $NUM_FILES) 
	do
		DST_F_NM=`printf "${DST_F_PREFIX}/sample512KB_%08g.html" $n`
		SRC_IDX=`expr $m \* $NUM_FILES + $n`
		SRC_F_NM=`printf "${SRC_F_PREFIX}/sample512KB_%08g.html" ${SRC_IDX}`
		ln -s $DST_F_NM $SRC_F_NM
	done
done
